# Generated by Django 4.2.20 on 2025-06-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_studentextra_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='department',
            field=models.CharField(blank=True, choices=[('Bsc.Physics', 'Bsc.Physics'), ('Bsc.Chemistry', 'Bsc.Chemistry'), ('Bsc.Botany', 'Bsc.Botany'), ('Bsc.Zoology', 'Bsc.Zoology'), ('Bsc.Mathmatics', 'Bsc.Mathmatics'), ('Bsc.Electronics', 'Bsc.Electronics')], max_length=30),
        ),
    ]
